### ISSUE TITLE
Can we get a footprint library please

### ISSUE THREAD

**Issue by JanZugic** [SolderedElectronics/Soldered-Inkplate-2-hardware-design#1]
i wish to create a custom case, but for that i need either a 3D model footprint library or a 3D model (preferably STEP) of the unit.

**Comment by JanZugic** [comment]
Its in  the outputs folder...

**Comment by rsoric** [comment]
Hi @JanZugic 

Glad you could find it, let us know if you might need something else for your case design.

-Rob

**Comment by JanZugic** [comment]
Hello! Are you located in Zagreb?

**Comment by rsoric** [comment]
Hi @JanZugic 

We are located in Osijek. If you want to get further in touch with us, we recommend the contact form on our website: https://soldered.com/contact/
