### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Soldered-Inkplate-2-hardware-design#3]
https://github.com/SolderedElectronics/Soldered-Inkplate-2-hardware-design/blob/d8ae98a4285a7189eac2a7881446ffaee9f6e620/README.md?plain=1#L5

umjesto:

https://github.com/SolderedElectronics/Inkplate-2-hardware-design/blob/main/OUTPUTS/V1.1.1/333166.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/Soldered-Inkplate-2-hardware-design/blob/main/OUTPUTS/V1.2.3/333166.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
